### ISSUE TITLE
Contribution Guide - avoid a need to configure github CLI

### ISSUE THREAD

**Issue by kgajowy** [xFAANG/askql#102]
```
Turn off autocrlf in your Git.
This is advised because some of the test files have Windows line endings on purpose and we would like to keep them there.
git config core.autocrlf false
```
This step from contribution guide can be avoided as long as we add 
```
{
  "endOfLine": "lf"
}
```
to `.prettierc` or config file.

[Source](https://prettier.io/docs/en/options.html#end-of-line)

// Willing to take this on.

**Comment by YonatanKra** [comment]
@kgajowy 
Great idea! We already have prettier in the project. Send a PR!
