### ISSUE TITLE
Build - pin dependencies

### ISSUE THREAD

**Issue by kgajowy** [xFAANG/askql#104]
Currently, dependencies are not pinned to a particular version. It may cause serious issues, as some breaking changes may happen even in `patch` updates. To ensure that every build remains the same, even if dependencies have not changed, we should pin them by removing `^` from `package.json` (and of course updating `.lock`). 
Otherwise, it may happen that triggering the very same build on different machines (depending on local `node_modules`) may lead to unpredicted issues.

Secondly, after pinning, I would recommend enabling [Dependabot](https://dependabot.com/) for constant updates to ensure stability and security. I used a few of similar services (like Renovate) and this one seems to be the most solid one.

**Comment by czerwinskilukasz1** [comment]
@kgajowy , pinning dependencies and running a Dependabot sounds like a great idea :) 
Given your experience, would you like to take care of it?

**Comment by kgajowy** [comment]
@czerwinskilukasz1 
Sure, feel free to assign me.

It's worth to mention, that existing PR would need to be carefully checked to avoid adding dependencies with `^`.

Dependabot would need to be added by one of core developers (its a github app)
