### ISSUE TITLE
Create an AskScript Playground

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#108]
We would like to let visitors on askql.org try programming in Ask as soon as possible.
The idea is to create a playground - an editor where a visitor can write or paste, instantly run AskScript and get the result.

**Comment by czerwinskilukasz1** [comment]
As Marcin mentioned to me in a private message, as for frontend, this editor looks cool. 
In addition, VS Code uses it for syntax coloring, so we could re-use syntax coloring plugin
https://microsoft.github.io/monaco-editor/

I'm saying: yes, this sounds great :).  And it's on MIT license, so we can freely reuse it.

**Comment by czerwinskilukasz1** [comment]
OK, working on this one.

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , according to [this issue](https://github.com/microsoft/monaco-editor/issues/1762), syntax highlighting in VS Code uses TextMates parsers which Monaco Editor uses JS regexes, at least for Python.
Do you have additional information on syntax coloring in these editors?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 I haven't looked into it. Whatever VS Code uses for syntax highlighting can support many programming languages so should be able to support AskScript as well

**Comment by czerwinskilukasz1** [comment]
> Whatever VS Code uses for syntax highlighting can support many programming languages so should be able to support AskScript as well
Of course.

**Comment by czerwinskilukasz1** [comment]
What I wanted to is that VS Code uses a different syntax coloring method, so we can't reuse syntax coloring from Monaco Editor. 
More info: [1](https://stackoverflow.com/questions/56254150/how-do-textmate-grammars-and-themes-work-with-vscode), [2](https://stackoverflow.com/a/44761887/330067)

**Comment by czerwinskilukasz1** [comment]
Here are official [examples of syntax coloring in Monaco](https://github.com/microsoft/monaco-languages) and here's [a playground](https://microsoft.github.io/monaco-editor/monarch.html).

**Comment by czerwinskilukasz1** [comment]
The short term plan for 1.1. was:
- Create any well-working and reasonably looking Playground, which can be used to run AskScript programs.
This is done.

My long term plans for AskScript Playground is:

- Get design update from Kari
- Add more examples to the Playground
- Use Monaco Editor
- Add syntax highlighting (which is a separate task from adding syntax highlighting in VS Code)
- Consider adding a window which allows to define own resources in Javascript (this is potentially dangerous, so we need a good discussion and plan)

What are your thoughts, @mhagmajer?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 the playground server PR is still open and I there is none for the client. Code needs to be merged into this repo so that everyone can participate.

Please discuss any changes to milestones with me and align your plans with the milestones.

**Comment by czerwinskilukasz1** [comment]
> Please discuss any changes to milestones with me and align your plans with the milestones.

Not sure what you mean as we are in constant contact.

Let me create a separate issue for each of the tasks in bullet points, so that we can assign them to milestones.

**Comment by czerwinskilukasz1** [comment]
Closing this one as done, the Playground is available at: http://cli.askql.org:3000/

Follow-ups are: 

- [Update design for Askscript Playground](https://github.com/xFAANG/askql/issues/173)
- [Add more examples to the Playground](https://github.com/xFAANG/askql/issues/181)
- [Use Monaco Editor in AskScript Playground](https://github.com/xFAANG/askql/issues/182)
- [Create a repository for AskScript Playground](https://github.com/xFAANG/askql/issues/183) (this includes publishing the source code of the Playground; needs to be done after Playground uses Monaco Editor)
- [Add syntax highlighting to AskScript Playground](https://github.com/xFAANG/askql/issues/184) (which is a separate task from adding syntax highlighting in VS Code)
- [AskScript Playground: Consider adding a window which allows to define own resources in Javascript](https://github.com/xFAANG/askql/issues/185) (this is potentially dangerous, so we need a good discussion and plan)

**Comment by mhagmajer** [comment]
Reopening since the linked PR is still open.

**Comment by czerwinskilukasz1** [comment]
Closing https://github.com/xFAANG/askql/pull/87.

**Comment by czerwinskilukasz1** [comment]
And closing this ticket.
