### ISSUE TITLE
Expand Contributing guidelines by add Global .gitignore file configuration

### ISSUE THREAD

**Issue by SebastianWesolowski** [xFAANG/askql#120]
Add information in Contributing guidelines about Global .gitignore file configuration.

example set of ignore file:
https://gist.github.com/jacobtomlinson/aace65a6920e44348d501da5e13a5a17

~~My propose file extension is add specific macOS file:~~
~~add .DS_Store~~

**Comment by czerwinskilukasz1** [comment]
Hi @SebastianWesolowski , good to see you here :) 
I fully support, would you like to submit a PR?

**Comment by kgajowy** [comment]
@czerwinskilukasz1 Just wondering if this should happen. Repository .gitignore should relate only to given project artifacts (like dist), instead of what potential developers environment might add (like `.idea` depending on IDE and similar).
I know it is a common practice but it should be the case for every developer to have local settings of `.gitignore` to avoid bloating this file with hundreds of things not related to the repository (.DS_Store is OS specific not project, same as IDE-related things)

I would recommend not to add to `.gitignore` anything that does not belong to the project itself.

**Comment by czerwinskilukasz1** [comment]
@kgajowy , thanks for your vigilance.  I totally forgot about the existence of .gitignore_global file!
Good point.

@SebastianWesolowski, kgajowy posted a sample minimal example above, which could work for you.
For a bigger set of ignores, take a look at: https://gist.github.com/jacobtomlinson/aace65a6920e44348d501da5e13a5a17
Do you see any reason for not using .gitignore_global for .DS_Store?

**Comment by SebastianWesolowski** [comment]
@kgajowy yes you have right, it is a common practice. I usualy add exclude this file. 

global ignore is the best practice. What about people who don't have a configured globalignore file ? 

It was usually add exclusion better for a project to  than to suggest best practices. in my work, it worked.

I have no experience with a project where more than 4 developers have worked. Is that very important in project like this ?

I saw project like GraphQL use too similar practice like ignore file DS_Store, but not all repositroy from  https://github.com/graphql


https://github.com/graphql/graphql-spec/blob/master/.gitignore
https://github.com/graphql/graphiql/blob/master/.gitignore

**Comment by mhagmajer** [comment]
I back up what @kgajowy said here. We can add gitignore global instructions in contributing.md

**Comment by SebastianWesolowski** [comment]
I didn't look at the problem from this perspective. 

Writing instructions on how to configure global gitingore file is better solution.

I be happy to write that instruction. Shall I continue in this thread or create a new issue?

**Comment by mhagmajer** [comment]
@SebastianWesolowski you can continue here, just rename the issue and update the description please :)

**Comment by czerwinskilukasz1** [comment]
@SebastianWesolowski , thanks for the contribution.
It's a good idea to link the PR with the issue, either by writing "closes #<issue id>" in the PR description (the word "closes" or [another closing word](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) is crucial), or by linking it manually on the PR page or the issue page:
![image](https://user-images.githubusercontent.com/12752520/84764882-b00d3200-afce-11ea-9e93-a837b9b7769a.png)

**Comment by czerwinskilukasz1** [comment]
Also, linking the PR before merging it automatically closes the issue :) 

Thanks for the contribution, we wish for more! :D
