### ISSUE TITLE
Add issue template for bug report

### ISSUE THREAD

**Issue by mhagmajer** [xFAANG/askql#126]
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by czerwinskilukasz1** [comment]
It's a part of #152

**Comment by dastin-sandura** [comment]
I will take care of this and use what @Tuhaj mentioned in #407 🙂 in comment https://github.com/xFAANG/askql/issues/407#issue-660212583
