### ISSUE TITLE
Add issue template for feature request

### ISSUE THREAD

**Issue by mhagmajer** [xFAANG/askql#128]
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by czerwinskilukasz1** [comment]
It's a part of #152

**Comment by dastin-sandura** [comment]
Hey @mhagmajer and @czerwinskilukasz1 can I take care of this issue? :)

**Comment by mhagmajer** [comment]
@dastin-sandura sure!

**Comment by dastin-sandura** [comment]
@mhagmajer I have submitted a PR with my proposed issue template. Let me know what you think 😄
