### ISSUE TITLE
Assigned value is discarded when exiting an inner scope

### ISSUE THREAD

**Issue by emklim** [xFAANG/askql#129]
```
ask {
    let a = 2

    let c = 'Hello'
    
    if(a < 5) {
        c = '!'
    }
    
    return c
}
```
returns `Hello`
instead of `!`

**Comment by czerwinskilukasz1** [comment]
Seems like a new value is discarded when exiting an inner scope, @mhagmajer ?

**Comment by mhagmajer** [comment]
Very interesting. Let's make sure that our test cases cover it. Thanks!

**Comment by czerwinskilukasz1** [comment]
Just added a test in this PR, which obviously fails:
https://github.com/xFAANG/askql/pull/147

**Comment by YonatanKra** [comment]
@mhagmajer 
I dug a little into the runner.
It seems like that `c = '!'` redeclares `c` with a `let`.
When running @czerwinskilukasz1 's test, I get this object:
```
[
  {
    "name": "let",
    "params": [
      "b",
      4
    ]
  }
]
```
In the statements inside `fun.ts` `compute` method.
Since it is a scoped `let` statement, it is, well... scoped :)

**Comment by YonatanKra** [comment]
Ok - the magic happens at `fun.ts`: https://github.com/xFAANG/askql/blob/master/src/askvm/resources/core/fun.ts#L12
It creates a new scope for the function, but does not take into account variables created in parent scope(s) (like `b` in the test).

**Comment by YonatanKra** [comment]
@mhagmajer  @czerwinskilukasz1 
Summary of my above rumbling:
Currently, the language has no way of knowing if you want to use the external scope or the internal one. So it just assumes you are using `let`, and thus creates a new scope for every `block`.
Do we want to allow this way of notifying weather it is a new `let` or just an assignment?

**Comment by mhagmajer** [comment]
@YonatanKra, the bug is related to the fact that we treat assignment and declaration of a new variable the same way - https://github.com/xFAANG/askql/blob/master/src/askjsx/lib/Set.tsx#L31. Currently in AskJSX `Set` stands for `let [...] = [...]` and `Assign` for `[...] = [...]`. We need to treat them differently.

**Comment by YonatanKra** [comment]
@mhagmajer 
So the bug is that b = 4 is treated as `let`?

**Comment by mhagmajer** [comment]
@YonatanKra yes, I have cut corners here and there when rushing to release 1.0 💁

**Comment by YonatanKra** [comment]
@mhagmajer bad you!!! ;)
Thing is - `b = 2` at the top is considered `let` as well. Should it be an error? Or does the language "swallow" such a thing, because `b` was never declared, it will be declared on first assignment?

**Comment by mhagmajer** [comment]
@YonatanKra I think we should throw a runtime error on when someone attempt to assign value to a undeclared variable. It's the same like trying to read an undeclared variable - we throw in that case already

**Comment by czerwinskilukasz1** [comment]
Congratulation, Ewa @emklim ! :). Your issue request was solved and merged! :D 🚀
