### ISSUE TITLE
for...in doesn't seem to execute the body

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#131]
Executing the following program:
```
ask {
    let mySum:float = 0
    for(let index in itemPrices) {
        const price = itemPrices:at(index)
        mySum = mySum:plus(price)
    }
    mySum
}
```

should lead to an error as `itemPrices` does not exist and is not defined as resource or value either.
Instead, this program returns 0.

**Comment by czerwinskilukasz1** [comment]
This issue is likely blocked by #129 .

**Comment by mhagmajer** [comment]
See https://github.com/xFAANG/askql/pull/212 for reference

**Comment by czerwinskilukasz1** [comment]
I am implementing for...of for arrays and objects, such that:
```
for (let a in [1, 2, 3, 'x', false, [4.5, 6]]) {
 log(a)
}
```
will output:
```
0
1
2
3
4
5
```

and 
```
for(let a in {a:1, b:2, c:3, d:'x', e:false, f:[4.5,6], g:{h:1, i:true}}) { 
  log(a) 
}
```
will output:
```
a
b
c
d
e
f
g
```

@mhagmajer , do you have any additional requests?

**Comment by mhagmajer** [comment]
Same as for-of. This should also work for strings I think

**Comment by czerwinskilukasz1** [comment]
Following our chat, this is how it should work for a string:
```
const word = 'Hello';
for(const index in word) {
 log(index);
}
```
