### ISSUE TITLE
for...of doesn't seem to execute the body

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#132]
Executing the following program:
```
ask {
    let mySum:float = 0
    for(let price of itemPrices) {
        mySum = mySum:plus(price)
    }
    mySum
}
```
should lead to an error as itemPrices does not exist and is not defined as resource or value either.
Instead, this program return 0.

**Comment by czerwinskilukasz1** [comment]
This issue is likely blocked by #129 .

**Comment by mhagmajer** [comment]
See https://github.com/xFAANG/askql/pull/212 for reference

**Comment by czerwinskilukasz1** [comment]
I am implementing for...of for arrays and objects, such that:
```
for (let a of [1, 2, 3, 'x', false, [4.5, 6]]) {
 log(a)
}
```
will output:
```
1
2
3
x
false
[ 4.5, 6 ]
```

and 
```
for(let a of {a:1, b:2, c:3, d:'x', e:false, f:[4.5,6]}) { 
  log(a) 
}
```
will output:
```
1
2
3
x
false
[ 4.5, 6 ]
```

@mhagmajer , do you have any additional needs?

**Comment by mhagmajer** [comment]
That looks about right 👍. This should also work with `const`. The result of the entire block may be empty like with `while`. Please test that return/break works correctly

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 also, please take a look at the `for` implementation and use it for reference - we probably don't need another resource for this and can implement it in AskJSX layer

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , what's the syntax for breaking from while?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 should be `break` similar to `return`

**Comment by czerwinskilukasz1** [comment]
`Uncaught Error: Unknown identifier 'break'!`
Filing it as: https://github.com/xFAANG/askql/issues/238

**Comment by czerwinskilukasz1** [comment]
> The result of the entire block may be empty like with `while`. 

Empty return value from `while` sounds inconsistent with `if`. Let's discuss it in issue https://github.com/xFAANG/askql/issues/239

**Comment by czerwinskilukasz1** [comment]
> @czerwinskilukasz1 also, please take a look at the `for` implementation and use it for reference - we probably don't need another resource for this and can implement it in AskJSX layer

While a regular `for` can be simply translated to a code block with the statements from for(.., .., ..) executed in the right places, for...of is far more complex and more type checking is needed (e.g. the value of `of` needs to be iterable, `key` should be a variable declaration etc., while quite general type definitions are used in Typescript definitions)

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 you should be able to do all that in AskJSX layer because a function in AskScript can be created to perform the for-of

**Comment by czerwinskilukasz1** [comment]
Of course I _can_ create it in AskJSX, the only question is how complex it's going to be.

I think it's very complex, let me post it in Discord and discuss it there.

**Comment by mhagmajer** [comment]
Ideally we should write it in AskScript using while :)

**Comment by czerwinskilukasz1** [comment]
I think it would be easier to write it in AskScript than in AskJSX, but we would need to use additional temporary variables, so either we would need to reserve some identifiers for internal use only (e.g. starting with $), or we would risk having a name clash with user program.
Also, defining them in AskScript means they would be even slower than now, and I'd say speed is something we should start taking into consideration or we end up being 100x times slower than Javascript or Ruby.
Why don't we just implement old good resources?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 declaration is something different than optimization. Maybe we should define it first and then think about optimization when we actually have some baseline?

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , what about the first part of my comment about the variables - what's your call?

**Comment by czerwinskilukasz1** [comment]
> @mhagmajer , what about the first part of my comment about the variables - what's your call?

Any thoughts on this one?

**Comment by czerwinskilukasz1** [comment]
Unless I'm missing something, I think the code will be very complex, something like:

```
export function ForOf({
  key,
  of: ofProp,
  children,
}: {
  key: AskCodeOrValue;
  of?: AskCodeOrValue;
  children: AskCodeOrValue[];
}) {
  if (!isAskCode(key)) {
    throw new AssertionError({
      message: 'forOf expects key to be a statement',
    });
  }
  if (typeof ofProp === 'undefined') {
    // Would have use assert, but then compiler complains that ofProp in <Let/> could be undefined.
    throw new AssertionError({ message: 'ofProp is undefined' });
  }

  return (
    <fragment>
      <Let name="$ofValue" value={Object.values({ ofProp })} />
      <Let name="$index" value={0} />
      <While
        condition={
          <Call
            name="<"
            args={[
              <ref name="$index" />,
              <call name="length" args={[<ref name="$ofValue" />]} />,
            ]}
          />
        }
      >
        {children}
        <Assign
          name="$index"
          value={<Call name="+" args={[<ref name="$index" />, 1]} />}
        />
      </While>
    </fragment>
  );
}
```

_plus_ the code above will work only if ofProp evaluates to an array or an object and would fail miserably in the middle of execution if it doesn't.. 

What I'm missing a lot here is a way to evaluate an expression using an equivalent of await runUntyped that I would have used if I implemented it as a new resource. 
Any hints, @mhagmajer ?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1, how would you implement `forOf` function in AskScript? AskJSX is a reflection of that.

If you find yourself in need of `run`, you might want to define your own function and then call it. Here's a sample while implementation in AskScript (based on native implementation of call):

```
const while = fun (condition, loopFun) {
  if (!condition) {
    return
  }
  loopFun()
  while(condition, loopFun)
}

**Comment by czerwinskilukasz1** [comment]
Following our chat, this is how it should work for a string:
```
const word = 'Hello';
for(const letter of word) {
 log(letter);
}
```
