### ISSUE TITLE
Add greaterThanOrEqual (>=) resource, similar to an existing lessThan (<) resource 

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#135]
There is src/askvm/resources/math/lessThan.ts, which is very good but there should also be greaterThanOrEqual.

Dear new contributor,

If you have any questions on how to start, please write a comment with a tag: @czerwinskilukasz1 or @mhagmajer, or join our Discord Community and let us know there. We will be very happy to help you start! :)

Cheers,
Łukasz (@czerwinskilukasz1)
AskQL Core Developer

**Comment by km4** [comment]
Try catch this issue :)

**Comment by km4** [comment]
PR on https://github.com/xFAANG/askql/pull/141

**Comment by km4** [comment]
@czerwinskilukasz1 @mhagmajer We can close this issue :)

**Comment by mhagmajer** [comment]
Thanks @km4!
