### ISSUE TITLE
Add a 'logicalOr' resource (|| binary operator)

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#136]
There are some operators in AskVM, e.g. 'lessThan' resource (< operator) (src/askvm/resources/math/lessThan.ts), but we are missing logical operators, like 'or' resource (|| operator).

Dear new contributor,

If you have any questions on how to start, please write a comment with a tag: @czerwinskilukasz1 or @mhagmajer, or join our Discord Community and let us know there. We will be very happy to help you start! :)

Cheers,
Łukasz (@czerwinskilukasz1)
AskQL Core Developer

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , do you have any comments on the name of the resource?

**Comment by mhagmajer** [comment]
This is the resource for logical alternative - accepts two booleans as arguments and returns a boolean. In JavaScript there is also bitwise alternative (OR) - done with the `|` operator. This would be another resource in AskScript. I don't know of other useful implementations of logical alternative that we might want to add on other data types. Also, we can have several aliases for resources. If we wanted to be very strict we could call it `booleanOr`. I'd be interested to also see what @kgajowy thinks about this.

**Comment by czerwinskilukasz1** [comment]
I'm fine with `booleanOr` if we have an operator for it.

**Comment by mhagmajer** [comment]
Let's keep well-known JS/C operators

`logicalOr` - `||`
`bitwiseOr` - `|`

**Comment by czerwinskilukasz1** [comment]
Moved `bitwiseOr` to https://github.com/xFAANG/askql/issues/244
