### ISSUE TITLE
Fix false positive tests

### ISSUE THREAD

**Issue by mhagmajer** [xFAANG/askql#148]
Some test have invalid `expectedResult`. This issue is about auditing all tests and fixing those.

**Comment by czerwinskilukasz1** [comment]
Yes, let's remove files .test.result.ts for all such tests.

**Comment by czerwinskilukasz1** [comment]
Please create issues for all such functionalities and list them here. Some of them already exist (e.g. issue with while).

**Comment by mhagmajer** [comment]
I'm going to write down here existing issues that are covered with these false positive tests.

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , what is the current status of this ticket?

**Comment by mhagmajer** [comment]
I'll get this done today
