### ISSUE TITLE
Run tests in an order

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#153]
Currently, tests are run by jest in a random order, so it's difficult to trace which tests were run from each directory.
It would be great to run them in some order (e.g. alphabetical by path).

![image](https://user-images.githubusercontent.com/12752520/84541878-93d07300-acf8-11ea-9196-e3fa6fd13f8f.png)

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 did you see https://jestjs.io/docs/en/cli.html#--runinband ? As we made AskScript a language that Jest can understand we can now enjoy all the CLI options of Jest, another open source MIT project in JavaScript :)

**Comment by YonatanKra** [comment]
@czerwinskilukasz1 running the tests in the same order is not such a good practice.
Running the tests in random order prevents test writers from writing tests that depend on each other.

**Comment by czerwinskilukasz1** [comment]
@YonatanKra , yeah, OK, I can see your point.
However, we still need to make sure they are independent by checking the newly created code.
Otherwise they might fail only when run in _some_ order, while succeeding when run in a different order.
How would you address it?

**Comment by mhagmajer** [comment]
Let's just not create tests that are dependant on each other. We can check this in a review process and also it's checked by CI that runs tests in parallel so it assumes that they don't have such dependencies. I think this one should be closed.
