### ISSUE TITLE
Add `test` and `expect` resources for fast and concise testing 🔧

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#154]
The following program should fail when run in CLI, however it succeeds. 
Moreover, the log() function doesn't seem to be called. I assume the whole function to test is not run at all.

This is a fast and concise way to define tests, it would be great if this worked soon.

```
🦄 .editor
// Entering editor mode (^D to finish, ^C to cancel)
  test('hello', fun () {
    log('Hello!')

    expect(2 + 2):toBe(4)
    expect(2 + 2):toBe(20)
  })

int ask(call(get('test'),'hello',fun(call(get('log'),'Hello!'),call(get('toBe'),call(get('expect'),call(get('+'),2,2)),4),call(get('toBe'),call(get('expect'),call(get('+'),2,2)),20))))
5
🦄 
```

**Comment by czerwinskilukasz1** [comment]
There is a related issue: #66

**Comment by mhagmajer** [comment]
Oh, man, you've just said that AskScript:
- is a fast and concise way to define tests
- it would be great if this worked soon

when compare to the current language that we use - TypeScript ❤️

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 what do you think about this sugar:

```
  test('hello') {
    log('Hello!')
    expect(2 + 2):toBe(4)
  })
```

**Comment by mhagmajer** [comment]
I'm gonna get it ready for the release on Monday

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 the fact that this program works in CLI comes from the fact that there is value `test` in the environment that returns `5`, not because tests are not implemented correctly. There are no resources for `test` so when you evaluate `test(arg)` you just receive the value `test`. Please consider updating the description

**Comment by czerwinskilukasz1** [comment]
@mhagmajer What is your idea for this one?
My proposal is to create a `test` resource that would execute its body until the first `expect`:`toBe` fails (returns false).
`expect` could be an identity function and `toBe(ex,act)` would fail if `ex != act`.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 we could implement `test` and `expect` ourselves or we could just link them from Jest. I suppose that the latter is easier for now

**Comment by czerwinskilukasz1** [comment]
@mhagmajer Sounds great, I didn't think of this kind of solution. 
Let me figure this out.
