### ISSUE TITLE
Add a linter to lint-staged 

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#165]
It will be great to have a linter check before committing files.

I would vote for eslint as it:

1. works with Typescript
1. is well-known
1. is well-supported
1. works with Prettier

Any comments?

Pointers:
- Add eslint and TS plugins ([see this page](https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration))
- Integrate with Prettier ([see this page](https://prettier.io/docs/en/integrating-with-linters.html))
- Add it to lint-staged ([see this page](https://github.com/okonet/lint-staged))
- Following [this comment](https://github.com/xFAANG/askql/pull/114#discussion_r440086123), please add a 'no-unused-...' rule straightway.

**Comment by km4** [comment]
I can take this issue. Maybe someone can pick me some hint ;)

**Comment by czerwinskilukasz1** [comment]
@km4 , great :)

**Comment by czerwinskilukasz1** [comment]
@km4 
I wrote a couple of pointers in the description, which are basically a sketch of the solution:
- Add eslint and TS plugins ([see this page](https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration))
- Integrate with Prettier ([see this page](https://prettier.io/docs/en/integrating-with-linters.html))
- Add it to lint-staged ([see this page](https://github.com/okonet/lint-staged))
- Following [this comment](https://github.com/xFAANG/askql/pull/114#discussion_r440086123), please add a 'no-unused-...' rule straightway.

If these are not sufficient, please ask specific questions - here or on [Discord](https://discord.gg/pYdzypH) :)

**Comment by km4** [comment]
@czerwinskilukasz1 what extensions we should lint?

**Comment by km4** [comment]
@czerwinskilukasz check this out #177 and add some feedback.

**Comment by km4** [comment]
If some problem with this code just feel free to call me 💪

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 feel free to close this one as you see fit
