### ISSUE TITLE
query examples in AskQL Overview don't work

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#172]
The following examples from [AskQL Overview](https://www.notion.so/AskQL-Overview-c95f3370be104466bfb3e3bca3ce7db4#6fb40d115c21468ca48e42c756d66b17) don't work:

```
ask {
	query {
		firstName
		lastName
		parents {
			firstName :formatString('c')
			lastName
		}
	}
}
```

```
ask {
	query {
		fullName :at('firstName') :concat(' ', lastName) :upperCase
	}
}
```

**Comment by czerwinskilukasz1** [comment]
I propose just removing formatString and adapting the 2nd example a bit.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 can you elaborate on "don't work"? What environment did you run these examples with and what was the expected and received output?

**Comment by czerwinskilukasz1** [comment]
@mhagmajer 

### Example 1.
Error in our [AskScript Playground](http://cli.askql.org:3000/): "Error: Unknown identifier 'formatString'!"

![image](https://user-images.githubusercontent.com/12752520/84818569-01411400-b017-11ea-88a6-1ead9e0d9a30.png)


This is the only place where `formatString()` is mentioned and there is no special environment mentioned, so it should be a built-in resource.

Therefore I suggest we remove `:formatString('c')` from the example.



### Example 2.
Error in our [AskScript Playground](http://cli.askql.org:3000/): "Error: Unknown identifier 'upperCase'!"

No special environment mentioned either, so I assume it's the default environment.
![image](https://user-images.githubusercontent.com/12752520/84818927-8c220e80-b017-11ea-9de2-14a167a499a9.png)

After fixing `upperCase` -> `toUpperCase`, I get:
```
{
  "fullName": "NULL SKYWALKER"
}
```
Notice "NULL" instead of the first name. This is because `:at('firstName')` doesn't make much sense there. I suggest to replace it with `firstName`.

**Comment by czerwinskilukasz1** [comment]
Fixed documentation
