### ISSUE TITLE
Pretty print AskCode

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#174]
When debugging, reading long lines of AskCode programs is difficult.
Instead of reading
```
block(let('c',call(get('concat'),call(get('get'),'c'),' :)')),let('a',call(get('+'),call(get('get'),'a'),1)))
```
it would be much easier to read:
```
block(
  let(
    'c',
    call(
      get(
        'concat'
      ),
      call(
        get(
          'get'
        ),
        'c'
      ),
      ' :)'
    )
  ),
  let(
    'a',
    call(
      get(
        '+'
      ),
      call(
        get(
          'get'
        ),
        'a'
      ),
      1
    )
  )
)
```

Implement a pretty-print for AskCode objects.

**Comment by mhagmajer** [comment]
Would prettier in JavaScript mode do the job here?

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , I don't know.  How do you use it?

**Comment by mhagmajer** [comment]
AskCode syntactically is a subset of JavaScript and TypeScript. When you run prettier on a JavaScript file containing the the code from description you get this:

```js
block(
  let('c', call(get('concat'), call(get('get'), 'c'), ' :)')),
  let('a', call(get('+'), call(get('get'), 'a'), 1))
);
```

This looks good enough to me - further customisation can be achieved with [options](https://prettier.io/docs/en/options.html). Let's not create custom implementation for formatting AskCode since prettier seems to do it already. You can run prettier using Node API as explained here https://prettier.io/docs/en/api.html.

**Comment by mhagmajer** [comment]
I have run into some issue regarding use of reserver keywords such as `if` and `while` when trying to run javascript prettier against .askcode file. I still think we should write a custom prettier plugin to deal with this though.

**Comment by czerwinskilukasz1** [comment]
How much time do you need to write it and how big the prettier plugin would be? The plugin for AskScript is over 200 lines of code.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 the plugin for AskCode would be much simpler - it's AST consists only of AskCode instances and simple values

**Comment by czerwinskilukasz1** [comment]
@mhagmajer How much time do you need to write it?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 I don't, this is not planned for any release yet so I haven't looked into it. Do you this should be done soon?

**Comment by czerwinskilukasz1** [comment]
@mhagmajer OK, so how about we proceed with my PR?

**Comment by mhagmajer** [comment]
Sure, I added comments. Can we keep this issue open after merging your PR for writing the actual prettier plugin?
