### ISSUE TITLE
Create an AskScript Playground from scratch

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#182]
The current editor is a giant hack, we want have clean and well-structured code, hence use the editor.
Some notes on the editor can be found here: https://github.com/xFAANG/askql/issues/108

**Comment by czerwinskilukasz1** [comment]
During my research it turned out that Monaco Editor does not support mobile devices. 
Also, Monaco Editor uses a completely different syntax highlighting than VS Code, so we'd need to implement it twice anyway, hence not much benefit from picking Monaco Editor.
Also, Playground should be playable on smartphones.

My pick is Ace editor, which is used in Cloud9, Amazon cloud-based IDE - so strong support guaranteed.
As for syntax highlighting for AskScript, good news too: "The Ace highlighting system is heavily inspired by the TextMate language grammar. ".
Moreover, they provide a tool which speeds up converting .tmlanguage file (used in VS Code) to their Ace highlighting system. This will likely mean much faster conversion.

**Comment by mhagmajer** [comment]
> During my research it turned out that Monaco Editor does not support mobile devices.

I'm not concerned about people not being able to type code from their mobile devices.

> Also, Monaco Editor uses a completely different syntax highlighting than VS Code

Can you explain how exactly? I'm confused because it says on the Monaco Editor website that "The Monaco Editor is the code editor that powers VS Code". I would assume that the VS Code uses all its features including the code highlighting.

> Also, Playground should be playable on smartphones.

Sure. Playing save code examples should not require people to do any code editing.

**Comment by czerwinskilukasz1** [comment]
>  I'm not concerned about people not being able to type code from their mobile devices.

I am. I think we shouldn't lock ourselves with an editor which doesn't support mobile if there are other editor doing a better job.

> Can you explain how exactly? I'm confused because it says on the Monaco Editor website that "The Monaco Editor is the code editor that powers VS Code". I would assume that the VS Code uses all its features including the code highlighting.

Could you trust me on this one?

**Comment by mhagmajer** [comment]
> I am. I think we shouldn't lock ourselves with an editor which doesn't support mobile if there are other editor doing a better job.

Can you give some examples of programming language playgrounds that officially support editing code on mobile phones and tablets?

> Could you trust me on this one?

The argument for Monaco Editor was precisely that it would save us work down the road. I'm still curious why you think that it "uses a completely different syntax highlighting than VS Code" while it is advertised as "The Monaco Editor is the code editor that powers VS Code". It just doesn't make sense to me. If you can give some pointers to what led you to this conclusion that would be helpful to understand the rationale behind this important decision.

Also please note that Ace editor is licensed under BSD which is more limiting than MIT.

**Comment by czerwinskilukasz1** [comment]
> Also please note that Ace editor is licensed under BSD which is more limiting than MIT.

According to Wikipedia, the main features are identical:
https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licences
Also, a number of sources are saying that in most cases they are equal.
What are the most important differences you have in mind?

**Comment by czerwinskilukasz1** [comment]
> The argument for Monaco Editor was precisely that it would save us work down the road. I'm still curious why you think that it "uses a completely different syntax highlighting than VS Code" while it is advertised as "The Monaco Editor is the code editor that powers VS Code". It just doesn't make sense to me. If you can give some pointers to what led you to this conclusion that would be helpful to understand the rationale behind this important decision.

I was also surprised.

Here is a couple of links which treat about this topic:
- https://stackoverflow.com/questions/56254150/how-do-textmate-grammars-and-themes-work-with-vscode
- https://github.com/NeekSandhu/monaco-textmate/issues/5
- https://stackoverflow.com/a/44761887/330067

**Comment by mhagmajer** [comment]
Thanks for the reference! I was able to pull up these suggestions from [a discussion group](https://groups.google.com/forum/#!topic/ballerina-dev/wNP46LRQGgQ):

> We currently have files in many formats describing ballerina grammar for many purposes.
>
> For syntax highlighting of composer which uses monaco editor we have to use [Monarch](https://microsoft.github.io/monaco-editor/monarch.html).
For the vscode plugin we use [Textmate](https://macromates.com/manual/en/language_grammars) grammar.
>
> So far we maintained two files describing ballerina in these grammars.
>
> To avoid the hassel of this I wrote a converter to convert from Textmate grammar to Monarch grammar. The converter script can be found [here](https://github.com/ballerina-platform/ballerina-grammar/blob/master/build-monarch.js).
>
> Both formats use a similar strategy.
> - They both apply rules to one line at a time from first line to last.
> - Both use regular expressions to match parts that should be highlighted.
> - Both can move to sub states after matching certain patterns.
>
> So this conversion is possible. 
> 
> Because Monarch grammar contains some additional features as well, the conversion is done from tm to Monarch rather than to the other side. Plus tm grammars are a well established format so tm grammar files are maintained for almost any mainstream language.

Do you think it would make sense to keep code highlighting definitions in one format and then automatically convert it into any other formats that we may need for other tools?

**Comment by mhagmajer** [comment]
I found some comparisons between Ace and Monaco Editor:
- ["The "bones" of Monaco are more robust and modern,"](https://github.com/Microsoft/monaco-editor/issues/19#issuecomment-228620925)
- ["TextMate isn't sufficient for many languages."](https://github.com/microsoft/vscode/issues/216)
- [suggestion to replace Ace with Monaco in Umbraco CMS for ASP.NET](https://github.com/umbraco/Umbraco-CMS/issues/6215)

Most notably, Monaco has an integrated way to add custom IntelliSense suggestions which may allow us to greatly improve the DX at some point. Here's how to add them https://mono.software/2017/04/11/custom-intellisense-with-monaco-editor/

**Comment by czerwinskilukasz1** [comment]
> Do you think it would make sense to keep code highlighting definitions in one format and then automatically convert it into any other formats that we may need for other tools?

Yes, I wrote already about this in my previous answers.

**Comment by czerwinskilukasz1** [comment]
We should keep it open until PR https://github.com/xFAANG/askql/pull/196 is merged.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 are we keeping Ace or Monaco here? You PR doesn't include code highlighting so at this point what are the arguments for Ace?
