### ISSUE TITLE
demoServer.ts should accept AskScript instead of AskCode 

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#191]
The variable askScriptCode in https://github.com/xFAANG/askql/blame/master/src/askExpressMiddleware/askExpressMiddleware.ts#L20 suggests AskScript should be accepted but actually the server throws syntax errors for AskScript programs, while accepting AskCode.

**Comment by mhagmajer** [comment]
@YonatanKra would you mind taking a look at this?

**Comment by mhagmajer** [comment]
It should be pretty simple fix anyway, @czerwinskilukasz1, feel free to take it

**Comment by YonatanKra** [comment]
@mhagmajer 
I'll take this one. It is clear when you look at the tests (a.k.a. the live documentation) but the variable name is misleading. I see the test file requires a small cleanup as well.
