### ISSUE TITLE
Add pre requirement to package.json

### ISSUE THREAD

**Issue by km4** [xFAANG/askql#192]
Now we have small pre requirement on this moment. Maybe we can add the this pre requirements to package.json ?

**Comment by mhagmajer** [comment]
What is the pre requirement?

**Comment by km4** [comment]
@mhagmajer https://github.com/xFAANG/askql#prerequisites :)

**Comment by mhagmajer** [comment]
@km4 oh yes, sure, if this can be said in package.json let's do it

**Comment by km4** [comment]
ok, challenge accepted:P

**Comment by mhagmajer** [comment]
Thanks @km4 and good luck 💪

**Comment by km4** [comment]
@mhagmajer we have some pre requirement version for npm ? we can add too

**Comment by mhagmajer** [comment]
I don't know about specific requirements, the Node version was picked at LTS for convenience. Wr use Node mostly for build tools

**Comment by km4** [comment]
I close this issue. Work is merged.
