### ISSUE TITLE
There is another package.json file in src/

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#218]
This is our main package.json file:
https://github.com/xFAANG/askql/blob/master/package.json

And this is the package.json file I think we should remove:
https://github.com/xFAANG/askql/blob/master/src/package.json

**Comment by czerwinskilukasz1** [comment]
@mhagmajer FYI

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 this should be file automatically generated for publishing to NPM only, not a source code
