### ISSUE TITLE
'break' resource is missing

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#238]
commit: f527c5cb (master, the latest commit)

Steps to reproduce:

In CLI run:
```
let a = 3
while(a<=5) {
  if (a >= 4) {
    break;
  }
  a=a+1
}
```

Expected: runs successfully

Actual: `Uncaught Error: Unknown identifier 'break'!`

**Comment by mhagmajer** [comment]
This should be implemented similarly to `return`

**Comment by czerwinskilukasz1** [comment]
@cpelican

**Comment by czerwinskilukasz1** [comment]
As for hints, I think it might be worth checking how `return` was implemented.

**Comment by cpelican** [comment]
Hi, I'd like to take this issue, thanks!
