### ISSUE TITLE
operator == is missing

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#241]
```
🦄 if (2==2) { return true}
Uncaught Error: Unknown identifier '=='!
    at Object.run (/Users/milimetr/Desktop/x/askql/src/askvm/lib/run.ts:29:12)
    at __awaiter (/Users/milimetr/Desktop/x/askql/src/askvm/lib/run.ts:4:12)
    at new Promise (<anonymous>)
    at /Users/milimetr/Desktop/x/askql/src/askvm/lib/run.ts:8:71
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/Users/milimetr/Desktop/x/askql/src/askvm/lib/run.ts:82:9)
🦄 
```

Dear new contributor,

If you have any questions on how to start, please write a comment with a tag: @czerwinskilukasz1 or @mhagmajer, or join our [Discord Community](https://discord.gg/pYdzypH) and let us know there. We will be very happy to help you start! :)

Hint #1: implement in a similar way to [lessThanOrEqual](https://github.com/xFAANG/askql/blob/master/src/askvm/resources/math/index.ts#L16)

Cheers,
Łukasz (@czerwinskilukasz1)
AskQL Core Developer

**Comment by mhagmajer** [comment]
Please not that because of data immutability and type awareness we won't need to have "strict equality" `===` operator in this language

**Comment by czerwinskilukasz1** [comment]
That's a good point.
@mhagmajer, so should our `==` work like Javascript's `===`?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 there is no operator in JavaScript that works exactly as equality should in AskScript because we'll actually do a deep comparison of immutable objects. Look at https://immutable-js.github.io/immutable-js/#equality-treats-collections-as-values for reference.

`{ a: 1 } == { a: 1}` should be `true`

**Comment by czerwinskilukasz1** [comment]
Could you write more examples here, so that we define `==`'s behavior?

What about `<` and other inequality operators. Would you like them to also perform a deep comparison? How?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 you can find more examples in the Immutable docs linked above. Deep comparison would work only for equality

**Comment by czerwinskilukasz1** [comment]
@mhagmajer  OK, so this implies there would be no equivalence between `a <= b && b <= a` and `a == b`, right?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 you can only use `<` for numbers, not objects I think

**Comment by czerwinskilukasz1** [comment]
@mhagmajer how about:
 - strings
 - booleans
Should the operator throw an error for these types, like in https://github.com/xFAANG/askql/pull/245 ?

**Comment by mhagmajer** [comment]
I think `2 == '4'` should be false. This is something that linting/static analysis could point out as an issue with code one day. At runtime it should not throw

**Comment by czerwinskilukasz1** [comment]
> @mhagmajer how about:
> 
> * strings
> * booleans
>   Should the operator throw an error for these types, like in #245 ?

Actually, I meant `<` here, e.g. check like: `'4' < '0'` or `false < true`.   Or `'4' < true`, `3 < true`.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 these types of comparison (using `<`) should only work for numbers. If there is some other way to compare other data types let's create separate functions/operators for those. I can imagine lexicographical comparison would be useful for sorting data

**Comment by czerwinskilukasz1** [comment]
Back to `==`, should this operator be equivalent to `equals` resource, therefore `equals` should be modified?

**Comment by mhagmajer** [comment]
Yes, `equals` should return false when comparing data of different type groups - eg. `2 != '2'`, but `2:toFloat ==2`

**Comment by czerwinskilukasz1** [comment]
> Yes, `equals` should return false when comparing data of different type groups - eg. `2 != '2'`, but `2:toFloat ==2`

Posted as a separate issue: https://github.com/xFAANG/askql/issues/343
