### ISSUE TITLE
Add a 'bitwiseOr' resource (| binary operator)

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#244]
There are some operators in AskVM, e.g. 'lessThan' resource (< operator) (src/askvm/resources/math/lessThan.ts), but we are missing bit operators, like 'bitwiseOr' resource (| operator).

Please note that bitwiseAnd (& operator) is listed here: https://github.com/xFAANG/askql/issues/374

Dear new contributor,

If you have any questions on how to start, please write a comment with a tag: @czerwinskilukasz1 or @mhagmajer, or join our Discord Community and let us know there. We will be very happy to help you start! :)

Cheers,
Łukasz (@czerwinskilukasz1)
AskQL Core Developer

**Comment by subedigaurav** [comment]
Hello @czerwinskilukasz1 , I am new and want to look into it. How do I start?

**Comment by czerwinskilukasz1** [comment]
Hello @subedigaurav , welcome to AskQL project.  
Thanks for asking how to start.  First how about you get familiar with the part of code you were going to work on. 
The description mentions an already existing operator (lessThan, implemented in src/askvm/resources/math/lessThan.ts). A good start would be to take a look at its code, understand more or less how it works and try to write bitwiseOr in a similar manner.  After that find out how `<` and `lessThan` were bound together and do a similar thing for `|`.
And the last thing would be to write tests which check whether your bitwiseOr resource and `|` operator work as intended. You could write the tests similar to the ones for `>` and `greaterThan` (we do have tests for `<` but they are not as great example):
https://github.com/xFAANG/askql/blob/master/src/askscript/__tests__/09-operators/operators-07-greater_than-oper.test.ts
https://github.com/xFAANG/askql/blob/master/src/askscript/__tests__/09-operators/operators-07-greater_than-res.test.ts

Let me know if you have more questions.

**Comment by subedigaurav** [comment]
@czerwinskilukasz1 thank you for the reply. I have figured out the implementation for the bitwiseOr. But I am confused about the tests. Do I need to write tests and test them myself or is it done automatically?

**Comment by km4** [comment]
Maybe helpful https://github.com/xFAANG/askql/issues/135 and pr for this

**Comment by subedigaurav** [comment]
thanks @km4 . I get it now. I will be creating my first pr soon. :)

**Comment by czerwinskilukasz1** [comment]
@subedigaurav , if you were wondering how to run the tests after you write them, please run:
```
npm run build
npm test
```

Of course re-running `npm run build` before `npm test` is only needed after you change files.
