### ISSUE TITLE
implement `mod` resource (% operator)

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#250]
If we have division and multiplication operators, we should also have a modulo operator. However, currently it does not exist.

```
🦄 40/6
float ask(call(get('/'),40,6))
6.666666666666667
🦄 40*6
int ask(call(get('*'),40,6))
240
🦄 .editor
// Entering editor mode (^D to finish, ^C to cancel)
40%6

Uncaught Error: Unknown identifier '%'!
    at Object.<anonymous> (/Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:70:15)
    at Generator.next (<anonymous>)
    at /Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:4:12)
    at Object.run (/Users/milimetr/Desktop/x/askql/dist/askvm/lib/run.js:29:12)
🦄
```

This task is to create a `mod` resource and a `%` operator linked to this resource. 

-- 

Dear new contributor,

If you have any questions on how to start, please write a comment with a tag: @czerwinskilukasz1 or @mhagmajer, or join our Discord Community and let us know there. We will be very happy to help you start! :)
Hint for starters: As a starting point, take a look at `src/askvm/resources/math/index.ts` file, where a `*` operator and `times` resource are already linked or a couple of other ones and use them as an example.

Cheers,
Łukasz (@czerwinskilukasz1)
AskQL Core Developer

**Comment by mhagmajer** [comment]
Are we sure that we want to add an operator for modulo? We could just have `mod` function or `a mod b` expression. I'm asking because `%` already has meaning associated to it by math.

**Comment by czerwinskilukasz1** [comment]
As for `%`, I'd mimic Javascript to be honest.

`a mod b` expression looks good, how about we allow to write: `a <funName> b` for any function name <funName>? 
 So that people could write also: `'a' concat 'b'` or `1 plus 3`?  It looks to me like Scala and I like it.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 we actually already have `a:concat(b)` and do what you described for operators. Let's maybe keep one way of doing things so people don't need to make choice when writing AskScript programs.

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , so I wouldn't introduce a new syntax `a mod b` for just one operation.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 sure, that would make AskScript easier for mathematicians which I think is an advantage.

So how about using % for percentage? I don't have strong opinion on this, however, just the fact that JavaScript uses this for modulo is not a sufficient argument for me here

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 also how about `a div b` so integer division?

**Comment by czerwinskilukasz1** [comment]
> @czerwinskilukasz1 sure, that would make AskScript easier for mathematicians which I think is an advantage.
> 
> So how about using % for percentage? I don't have strong opinion on this, however, just the fact that JavaScript uses this for modulo is not a sufficient argument for me here

I can't think of a better operator.  Also, at least 20 other programming languages, including C/C++, C#, Java, Python, PHP and Kotlin, are using % for modulo.

As for percent, I'm totally not sure how we could use it.



> @czerwinskilukasz1 also how about `a div b` so integer division?

So for what class of operations you would use it?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1

`7 / 3 = ((7 div 3) * 3) + (7 mod 3)`

About `%` we could say

`let price = 1000 * 20%`

I guess this would only make sense as a unary operator so the binary can be used for module. Would it be possible for the parser to support both?

**Comment by czerwinskilukasz1** [comment]
> @czerwinskilukasz1
> 
> `7 = ((7 div 3) * 3) + (7 mod 3)`

I see, I see. Looks pretty good.  
So, would we just hardcode it into AskScript grammar for just `div` and `mod` or rather for all identifiers? 


> About `%` we could say
> 
> `let price = 1000 * 20%`

I'm not convinced to this.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 let's do it in parser only for operators, `div` and `mod` and carry the discussion about unary `%` on a separate issue

**Comment by czerwinskilukasz1** [comment]
`%`: https://github.com/xFAANG/askql/issues/264

**Comment by czerwinskilukasz1** [comment]
As for `a mod b` and `a div b` syntax, I moved it to issue https://github.com/xFAANG/askql/issues/411

**Comment by czerwinskilukasz1** [comment]
@develper , following [your comment](https://github.com/xFAANG/askql/issues/395#issuecomment-664325826), this issue is yours :)
If you had any questions, just tag me here.

**Comment by develper** [comment]
@czerwinskilukasz1 , I have implemented the mod resource and want to know should I write tests for the same? If yes, then which test cases I should include.

**Comment by czerwinskilukasz1** [comment]
> @czerwinskilukasz1 , I have implemented the mod resource and want to know should I write tests for the same? If yes, then which test cases I should include.

Great.  

Let's add an example of `<int> % <int>` whose result should be 0, an example of `<int> % <int>` whose result should be non-zero, an example of `<float> % <int>` and `<float> % <float>`.
The same tests should be written twice for AskScript - once for `mod()` resource and once for `%` operator.
See `src/askscript/__tests__/09-operators/operators-09-logicalOr-oper.test.ts` and `src/askscript/__tests__/09-operators/operators-09-logicalOr-res.test.ts` for an example of such tests.
