### ISSUE TITLE
toInt doesn't convert numbers to integer

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#269]
```
🦄 2.3:toInt
float ask(call(get('toInt'),2.3))
2.3
🦄 
```

Dear Contributor,

This task has evolved a bit. Please read the comments to find out the latest description.

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , was your intention to create a real `toInt` or rather `toNumber`?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 this should round floats to be integers, I confirm that this is a bug in implementation of `toInt`

**Comment by czerwinskilukasz1** [comment]
@mhagmajer 
Actually, I wasn't sure because we already have `floor` and `ceil`:

```
🦄 floor(2.3)
int ask(call(get('floor'),2.3))
2
🦄 ceil(2.3)
int ask(call(get('ceil'),2.3))
3
🦄 
```

So maybe we could just remove `toInt` entirely and introduce `toNumber` instead, which would convert any _reasonable_ type to int | float?
```
toNumber('2.3')  = 2.3 (float)
toNumber(2.3) = 2.3 (float)
toNumber('2') = 2 (int)
toNumber(2) = 2 (int)
toNumber('a') = NaN
toNumber([]) = NaN

**Comment by mhagmajer** [comment]
I'd like to live it up to user to decide to if they want int or float because these types will be dealt with differently by runtime

**Comment by mhagmajer** [comment]
`floor` and `ceil` should only work on numbers

**Comment by czerwinskilukasz1** [comment]
OK, tickets added 😄

**Comment by czerwinskilukasz1** [comment]
So back to `toInt`, should:
 - `toInt(2.6)` return `2` or `3`?
 - `toInt('2.6')` return `2` or `3`?
 - `toInt(true)` return `1`?
 - `toInt(false)` return `0`?
 - `toInt(null)` return `0`?
 - `toInt([])` return `0`?
 - `toInt([1])` throw?
 - `toInt([1,2])` throw?
 - `toInt({a:1})` throw?
 - `toInt({a:1, b: 2})` throw?

**Comment by czerwinskilukasz1** [comment]
I'd think it's a good default, since programmers are used to it and at the same time I don't see big no's against.

**Comment by mhagmajer** [comment]
Let's throw on complex types such is array or struct. Not all strings should be supported to

**Comment by czerwinskilukasz1** [comment]
> Let's throw on complex types such is array or struct. Not all strings should be supported to

Could you elaborate a bit more?

**Comment by mhagmajer** [comment]
non number strings should just throw IMHO `toInt('4a')`
all complex types - arrays, objects should throw `toInt([])`

**Comment by czerwinskilukasz1** [comment]
Ah, OK, understood. 

OK, so the task goes as follows:

In case a non-number string or an array or an object is passed to `toInt`, it should throw an Error().
Otherwise, it should mimic Math.round() from Javascript.

Meaning:
 - `toInt(2.3)` returns `2`
 - `toInt('2.3')` returns `2`
 - `toInt(2.5)` returns `3`
 - `toInt('2.5')` returns `3`
 - `toInt(-2.5)` returns `-2`
 - `toInt('-2.5')` returns `-2`
 - `toInt(-2.51)` returns `-3`
 - `toInt('-2.51')` returns `-3`
 - `toInt('4a')` ~returns `NaN`~  throws an Error
 - `toInt('abc')` ~returns `NaN`~  throws an Error
 - `toInt(true)` returns `1`
 - `toInt(false)` returns `0`
 - `toInt(null)` returns `0`
 - `toInt([])` ~returns `0`~  throws an Error
 - `toInt([1])` ~returns `1`~  throws an Error
 - `toInt([1,2])` ~returns `NaN`~  throws an Error
 - `toInt({a:1})` ~returns `NaN`~  throws an Error
 - `toInt({a:1, b: 2})` ~returns `NaN`~  throws an Error

**Comment by RichardM99** [comment]
@czerwinskilukasz1 

I can take this one as per your suggestion.

**Comment by RichardM99** [comment]
@czerwinskilukasz1 

Regarding the tests;

the `math` dir has it's own `_tests_` dir - is it sufficient to have test coverage for `toInt` there, or is it also necessary to have test coverage in `askscript/_tests_` ?

**Comment by czerwinskilukasz1** [comment]
> @czerwinskilukasz1
> 
> Regarding the tests;
> 
> the `math` dir has it's own `_tests_` dir - is it sufficient to have test coverage for `toInt` there, or is it also necessary to have test coverage in `askscript/_tests_` ?

Great question. It's always better to have a few more tests but it will be enough to just write tests in `math`.  
The reason I asked for tests in `askscript/__tests__` in a ticket with one of the operators was that an operator was attached to the resource, so I wanted the tests to verify that both the resource and an AskScript-like way of using operators work.
