### ISSUE TITLE
Playground: add HTTPS

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#283]
Our New Playground (http://cli.askql.org/) is working fine, but is missing HTTPS.

**Comment by czerwinskilukasz1** [comment]
FYI @Tuhaj  :)

**Comment by czerwinskilukasz1** [comment]
My idea is to run a Greenlock express server on the same VPS. It will automatically issue an SSL certificate from a free Let's Encrypt service and renew it.

**Comment by km4** [comment]
I propose to add Cloudflare for encrypted SSL/TLS domain,

It's free and we can add encrypts end-to-end, using a CF certificate on the server.

**Comment by czerwinskilukasz1** [comment]
Thanks.   In the meantime I had a chat with Marcin and we decided to try and publish Playground on Netlify. It is already taking care of our *.askql.org SSL, so we should get it out-of-the-box.

**Comment by czerwinskilukasz1** [comment]
This is done now.
