### ISSUE TITLE
Add '!' to valid characters for operators

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#295]
When I run:
```
ask {
    if (2!=2) { return true}
}
```

I got:
```
)
ask {
    if (2!=2) { return true}


SyntaxError: Expected " ", ")", ",", ".", ":", "\n", "\r", "\t", [/], [0-9], or [\-<>+*\^%=&|] but "!" found.
Location: {
  "start": {
    "offset": 15,
    "line": 2,
    "column": 10
  },
  "end": {
    "offset": 16,
    "line": 2,
    "column": 11
  }
}
```

Shouldn't we add '!' to valid characters for operators?

**Comment by czerwinskilukasz1** [comment]
I am for it.
@mhagmajer ?

**Comment by mhagmajer** [comment]
Sure! Let's add it.

Exclamation mark can often also be used as a prefix unary operator:

```
!false // not(false)
!true // not(true)
!(n < 5) // not(n < 5)
```

Do you think that our grammar could support unary prefix operators? This would help solve https://github.com/xFAANG/askql/issues/298

**Comment by czerwinskilukasz1** [comment]
Description of the task:
This should be simple, just add `!` to the allowed characters in .pegjs file
