### ISSUE TITLE
unequality (operator != or <>) is missing

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#296]
```
ask {
    if (2<>2) { return true}
}
```
results in:
```
Error: Unknown identifier '<>'!
```

The task is to implement unequality. 

Some discussion is needed to decide whether we add `!=` or rather `<>`. Depends on discussion in https://github.com/xFAANG/askql/issues/295 .

**Comment by mhagmajer** [comment]
I guess `!=` is known better :)

**Comment by czerwinskilukasz1** [comment]
Blocked on #295

**Comment by czerwinskilukasz1** [comment]
I guess != should call not(equals()), right, @mhagmajer ?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 yes, sure

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , we have a number of operators defined in src/askvm/resources/math/index.ts and I think it would be the most logical to place `!=` there. 
However, I can't figure out how to define `!=` as `not(equals())` there. Would I need to implement a separate resource? How could I refer to `not` and `equals` resources there?

Another option would be to define `!=` somewhere in askjsx, but I guess I would need to write an ugly if in `src/askjsx/lib/Call.tsx` which would support just `!=` and no other operators.  I'm not a fan of this solution.

What's your advice?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 let's just create `notEquals` resource for now and then simplify it later on

**Comment by czerwinskilukasz1** [comment]
Blocked on #295
