### ISSUE TITLE
-n / -(n) doesn't parse

### ISSUE THREAD

**Issue by mhagmajer** [xFAANG/askql#298]
```
🦄 -test
Uncaught Error [SyntaxError]: Expected [0-9] but "t" found.
Location: {
  "start": {
    "offset": 7,
    "line": 2,
    "column": 2
  },
  "end": {
    "offset": 8,
    "line": 2,
    "column": 3
  }
}
```

Expected: negative value of `test`

If we reworked prefix unary operators, then it would help in other areas such as `+4` which also doesn't parse. If unary minus was an operator rather than part of number's grammar rule we could solve the plus problem very easily.

Tip from JS: `2++4` doesn't work, but `2+(+3)` does

**Comment by mhagmajer** [comment]
Fun observation - we already support postfix unary operator with colon `:`

```
false:not // true
(2 < 3):not // false
```

So if `!` was an alias for `not` we could say

```
false:!
(2 < 3):!
```

I guess what's needed for the prefix unary is just the `<operator><identifier>` grammar rule

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , yes, `-` is a part of a number.
And yes, if we wanted to support `-n`, the best way is to implement unary operators, probably by introducing a `<operator><identifier>` grammar rule.
