### ISSUE TITLE
add == operator for equality

### ISSUE THREAD

**Issue by mhagmajer** [xFAANG/askql#299]
Similarly to https://github.com/xFAANG/askql/issues/137, let's add `==` operator as an alias for `equals` resource

```
false == false
```

should be true, but throws with `Unknown identifier '=='!`

**Comment by czerwinskilukasz1** [comment]
@mhagmajer Isn't this issue a duplicate of https://github.com/xFAANG/askql/issues/241 ?

**Comment by czerwinskilukasz1** [comment]
As for parsing errors, I'm getting an 'Unknown identifier error':

```
🦄 false == false
Uncaught Error: Unknown identifier '=='!
```
 which is expected if there is no `==` defined

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 yes, you're right I updated the description
