### ISSUE TITLE
2<ws>+<ws>3 does not parse

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#30]
While `2+3` works, `2 + 3` does not.  Whitespaces.

**Comment by czerwinskilukasz1** [comment]
Output from AskScript CLI:

```$ node dist/cli.js
🦄 2+3
int ask(call(get('+'),2,3))
5
🦄 2+ 3
int ask(call(get('+'),2,3))
5
🦄 2 + 3
Uncaught:
[Error [SyntaxError]: Expected " ", ".", "//", ":", ";", "\n", "\r", "\t", or "}" but "+" found.
Location: {
  "start": {
    "offset": 8,
    "line": 2,
    "column": 3
  },
  "end": {
    "offset": 9,
    "line": 2,
    "column": 4
  }
}
] {
  name: 'SyntaxError',
  message: 'Expected " ", ".", "//", ":", ";", "\\n", "\\r", "\\t", or "}" but "+" found.\n' +
    'Location: {\n' +
    '  "start": {\n' +
    '    "offset": 8,\n' +
    '    "line": 2,\n' +
    '    "column": 3\n' +
    '  },\n' +
    '  "end": {\n' +
    '    "offset": 9,\n' +
    '    "line": 2,\n' +
    '    "column": 4\n' +
    '  }\n' +
    '}'
}```

**Comment by matheusmonte** [comment]
Can I get this to solve?

**Comment by czerwinskilukasz1** [comment]
@matheusmonte , sure thing. Sold! :)

**Comment by czerwinskilukasz1** [comment]
Hi @matheusmonte , how is writing the fix going?  Do you need any pointers?

**Comment by mhagmajer** [comment]
@matheusmonte if you don't confirm and give some ETA by the end of this week, we'll need to take over. Thanks for understanding!

**Comment by matheusmonte** [comment]
Hey, Sorry for this, I have some personal problems, and need to be offline for a while. If is good for your, I can take care of this until next Wednesday 10 june.

**Comment by czerwinskilukasz1** [comment]
Hey, Matheus, how are things? How about a small contribution? :) 
I think this https://github.com/xFAANG/askql/issues/378 or this one https://github.com/xFAANG/askql/issues/369 might be interesting for you.

@matheusmonte
