### ISSUE TITLE
Implement 'min' resource 

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#369]
There is [`max`](https://github.com/xFAANG/askql/blob/master/src/askvm/resources/math/max.ts) in Ask, but there is no `min`.

Hint: use `max` ([link](https://github.com/xFAANG/askql/blob/master/src/askvm/resources/math/max.ts)) as an example for `min`.

**Comment by 199201shubhamsahu** [comment]
Would like to contribute.
What else needs to be done other than creating the min.ts resource, and testing that it works in the cli?

**Comment by czerwinskilukasz1** [comment]
Congrats, Shubham 🙂
