### ISSUE TITLE
[askvm] 'fetch' resource should not download a hardcoded URL

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#370]
Currently, [fetch resource](https://github.com/xFAANG/askql/blob/master/src/askvm/resources/node/fetch.ts) always downloads https://jsonplaceholder.typicode.com/posts/1 instead of an URL from the argument.

**Comment by RichardM99** [comment]
@czerwinskilukasz1 I can take if that's ok? 🙃

**Comment by czerwinskilukasz1** [comment]
Hello Richard, you got it! 😃

**Comment by czerwinskilukasz1** [comment]
@RichardM99 , out of curiosity, how did you find AskQL repository? We are working on making it a bit more popular and I was wondering which way worked in your case.

**Comment by RichardM99** [comment]
@czerwinskilukasz1 

Thank you 🙃 

It came up on my twitter feed because I follow https://twitter.com/first_tmrs_only

**Comment by czerwinskilukasz1** [comment]
Great, thanks for feedback :) 
Also, feel free to give feedback to *us*. There are probably tons of things we could improve.  You can write here or via a message on our Discord: https://discord.gg/pYdzypH
