### ISSUE TITLE
'each' resource is a noop

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#372]
https://github.com/xFAANG/askql/blob/master/src/askvm/resources/core/each.ts

```
export const each = resource({
  type: any,
  resolver: async () => null,
});
```

**Comment by czerwinskilukasz1** [comment]
Hi @Fifciu , would you like to take a look at this issue? :)

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 what is the expected behaviour of `each`?

**Comment by czerwinskilukasz1** [comment]
Right.

My proposal is the following:
`each` should accept 2 arguments: an array and a function, which should be applied on each of the elements of the array.
Function signature should be: `fun(t: char, index: number, firstArrayElement: boolean, lastArrayElement: boolean):any`. 
The result values are disregarded.

Example:
```
  const lorem = 'lorem ipsum dolor sit amet consectetur adipiscing elit'
  lorem:split(' '):each( fun(t: char, index: number, firstArrayElement: boolean, lastArrayElement: boolean) {
	  const cap = t:toUpperCase
    if (last) {
      result = result + cap
    } else {
      result = result + concat(cap, ' ')
    }
  })
```

@mhagmajer , any thoughts?

**Comment by YonatanKra** [comment]
Why first and last?
Why not just do like the JS forEach function?
`(item: any, index: number, array: any[]) => {}`

**Comment by mhagmajer** [comment]
I like @YonatanKra proposal of following the JS signature

**Comment by czerwinskilukasz1** [comment]
Me too.
