### ISSUE TITLE
Add a 'bitwiseAnd' resource (& binary operator)

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#374]
There are some operators in AskVM, e.g. 'lessThan' resource (< operator) (src/askvm/resources/math/lessThan.ts), but we are missing bit operators, like 'bitwiseAnd' resource (& operator).

Please note that bitwiseOr (| operator) is listed here: https://github.com/xFAANG/askql/issues/244

Dear new contributor,

If you have any questions on how to start, please write a comment with a tag: @czerwinskilukasz1 or @mhagmajer, or join our Discord Community and let us know there. We will be very happy to help you start! :)

Cheers,
Łukasz (@czerwinskilukasz1)
AskQL Core Developer

**Comment by akeni** [comment]
@czerwinskilukasz1 are you looking to bitwise AND two variables that are type numbers?

**Comment by mhagmajer** [comment]
@akeni yes, that resource should take two ints, look at their bits and perform bitwise AND [like JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_AND)

**Comment by akeni** [comment]
@czerwinskilukasz1 I am having issues with PR LINT test. Where can i read docs to write subject lines for it?

**Comment by czerwinskilukasz1** [comment]
Hello @akeni , in case or PR lint tests and other checks inside the PR, 
the best place to start is to look at the details in the PR:

![image](https://user-images.githubusercontent.com/12752520/87303567-add9bd00-c513-11ea-93b8-2912c1db2b67.png)

The most recent results were saying:
![image](https://user-images.githubusercontent.com/12752520/87303609-bfbb6000-c513-11ea-8186-191faa0b44eb.png)

I just renamed the title of your PR from:
'feat(askvm): Add a 'bitwiseAnd' resource (& binary operator)'
to:
'feat(askvm): **add** a 'bitwiseAnd' resource (& binary operator)'

and now the check is green :)
![image](https://user-images.githubusercontent.com/12752520/87303719-e4173c80-c513-11ea-815b-606c5a17a006.png)

I will comment on the PR itself on the PR page.

**Comment by czerwinskilukasz1** [comment]
Closed with @akeni 's PR
