### ISSUE TITLE
[askscript] Array value gets merged with the previous line

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#382]
Consider the following program:
```
ask { 
    'abcd'
    [1]
} 
```

The expected return value is `[1]`.
The actual return value is `b`. 
Why? Because we treat newlines like any other whitespace, so
```
'abcd'
    [1]
```
is seen the same as 
``` 'abcd' [1] ```
and
``` 'abcd'[1] ```, which is obviously 'b'.

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 how do you intend to solve it? Seem like either the program is missing `;`/`,` or the new line should be treated as semicolon but it isn't

**Comment by czerwinskilukasz1** [comment]
As you can see in [my PR](https://github.com/xFAANG/askql/pull/383), I prevented newline from being a valid whitespace for `value ws* [index]` constructs (where `ws` stands for whitespace).
We had the same case a month ago with `-`. 
```
123
-123
```
was treated as `123-123`, which didn't make sense nor was it logical.
I would say this is the best we can do for now.
