### ISSUE TITLE
syntax error while building in windows

### ISSUE THREAD

**Issue by subedigaurav** [xFAANG/askql#395]
While running `npm run build` in Windows, command `rm` is not recognized at:
`rm -rf dist/playground && mkdir -p dist/playground/public && npm run playground:build-assets && npm run playground:build-ts && ts-node scripts/playgroundPostBuild.ts`

Possible solution:
Create OS agnostic build command/s.

**Comment by mhagmajer** [comment]
Thanks @subedigaurav. You're right that this need to be changed into OS ognostic build command such as https://github.com/xFAANG/askql/blob/master/scripts/preBuild.ts#L5

**Comment by czerwinskilukasz1** [comment]
Hint: As [YonatanKra mentioned](https://discord.com/channels/688128418914500838/704117328735895662/733196381748985936), 'Under scripts/utils there's a removeRecursive util that is OS agnostic'.

**Comment by develper** [comment]
Hi @mhagmajer. I would like to take on this issue.

**Comment by mhagmajer** [comment]
Sure @develper, it's yours :)

**Comment by czerwinskilukasz1** [comment]
@develper , congrats for your first contribution! 🙂  🚀 
How did you like it?
Would you have any feedback for us on what to improve in the process?

**Comment by subedigaurav** [comment]
@develper good job on the issue. 🚀
@czerwinskilukasz1 there is still an issue with the following command while building:
`tsc && mv dist/playground/public/assets/js dist/playground/public/js`

Maybe this could be made OS agnostic as well?

**Comment by develper** [comment]
Thanks @czerwinskilukasz1 and @subedigaurav ,I had an amazing experience.

I was able to follow contributing guidelines without any hassle. It is well documented. However, if I find any improvement later I will let you know.

Also, feel free to tag me on an issue which is beginner friendly(like me).

**Comment by czerwinskilukasz1** [comment]
> @develper good job on the issue. 🚀
> @czerwinskilukasz1 there is still an issue with the following command while building:
> `tsc && mv dist/playground/public/assets/js dist/playground/public/js`
> 
> Maybe this could be made OS agnostic as well?

@subedigaurav , thanks for your suggestion.  I would say `mv` is OK to stay if Windows, Linux and MacOS all support it. It seems they do, so I would leave it how it is now. However, there is currently 151 other issues to contribute to. Let me know if you would like a suggestion, which are good ones for now.

**Comment by czerwinskilukasz1** [comment]
> Thanks @czerwinskilukasz1 and @subedigaurav ,I had an amazing experience.
> 
> I was able to follow contributing guidelines without any hassle. It is well documented. However, if I find any improvement later I will let you know.

@develper, thanks for your kind words. For sure we have room to improve, we are eager to hear your feedback.


> Also, feel free to tag me on an issue which is beginner friendly(like me).

Great, let's make it happen :)   I am wondering if you like parsers (we use PEG.js), if so, how would you like this one: https://github.com/xFAANG/askql/issues/51, and if you are more into just regular code, maybe you will like this: https://github.com/xFAANG/askql/issues/250?

**Comment by develper** [comment]
@czerwinskilukasz1, #250 sounds good to me.
