### ISSUE TITLE
[playground] See 'Values and Resources' here leads to 404

### ISSUE THREAD

**Issue by mhagmajer** [xFAANG/askql#398]
Currently the resources link on https://cli.askql.org/.leads to
https://github.com/xFAANG/askql/blob/master/src/demoAskScriptServer.ts#L21 which results in. 404 instead of information about available values and resources

**Comment by czerwinskilukasz1** [comment]
I'll take it

**Comment by czerwinskilukasz1** [comment]
Good catch, @mhagmajer !
