### ISSUE TITLE
Implement `hasKey` resource

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#400]
I wanted to write a piece of code that in Javascript looks like this:
```
if (!(a in leftMostPosition)) {
   leftMostPosition[a] = i;
}
```
Alas, I couldn't find any way to express it, because I didn't find a resource for it.
Please note that comparing `leftMostPosition[a]` with any value would not work as there is no `undefined` value in AskScript, only `null`, which could be a legitimate value of `leftMostPosition[a]`.

**Comment by czerwinskilukasz1** [comment]
@mhagmajer

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 would the following make sense? We would need a `hasKey` resource for that

```
if (not(leftMostPosition:hasKey('a'))) {
   leftMostPosition[a] = i;
}
```

**Comment by czerwinskilukasz1** [comment]
`hasKey` sounds good to me. Renaming the task.

**Comment by czerwinskilukasz1** [comment]
Task:

Implement a `hasKey` resource.   All list-related resources live in [`src/askvm/resources/list`](https://github.com/xFAANG/askql/tree/master/src/askvm/resources/list) directory. Check other resources from the directory to grasp how they work.

**Comment by cpelican** [comment]
Hi, I would be interested in doing this issue, is it ongoing? Thanks!

**Comment by czerwinskilukasz1** [comment]
Hello @cpelican , it sounds awesome!

**Comment by czerwinskilukasz1** [comment]
The issue is yours. 
In addition to creating code to `hasKey`, please write also a test file (or a couple) in AskScript language in [src/askscript/__tests__/07-arrays](https://github.com/xFAANG/askql/tree/master/src/askscript/__tests__/07-arrays).
Let me know if you have any questions. We would love to hear feedback, e.g. if we are missing some documentation or guides for new contributors.

**Comment by cpelican** [comment]
Hi @czerwinskilukasz1, I just added tests in `src/askscript/__tests__/07-arrays`, but before that i had noticed there were tests in `askvm/resources/list/`, so i had added some tests also there. Is it a problem? Thanks!

**Comment by czerwinskilukasz1** [comment]
Hi @cpelican ,

> Hi @czerwinskilukasz1, @mhagmajer, I would have 2 questions:
> 
> * I just added tests in `src/askscript/__tests__/07-arrays`, but before that i had noticed there were tests in `askvm/resources/list/`, so i had added some tests also there. Would you prefer if all tests were in the same directory or do these both places have different purposes?

Yeah, great question. So, tests in `src/askscript/__tests__` are testing AskScript language, while tests in `src/askvm/**/__tests__` test more low-level AskVM resources and the code is written in AskCode.  Think of AskCode as an "assembler" for AskVM, while AskScript is a user-facing language (like C# or Javascript). Here is a diagram showing how different they look:
![askQL-diagram](https://user-images.githubusercontent.com/12752520/88469894-69c4c000-cef6-11ea-825e-95a40532d557.jpg)


Also, tests in AskCode we write are usually much much shorter, limited to just one expression, while tests in AskScript tend to be a complete program.

> * The place where the code belongs indicates me this resource should apply to a `list` or `array`.
This is a good remark. I would save the resource in `src/askvm/resources/list` for now, but be prepared @mhagmajer might propose a better place after you create your PR.

> But the use case of this issue made me think that this could be used for objects as well. Would you like it to work only on `arrays` or also on `objects`?
Great question. Yeah, I should have be more clear. I meant both arrays and objects.

**Comment by cpelican** [comment]
@czerwinskilukasz1 ok, thank you for your answer!
