### ISSUE TITLE
if block without braces silently executes wrong branch

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#403]
Consider the following AskScript program:
```
ask {
  const n = 3
  if ((n==0) || (n == 1))
    return true
  
  return false
}
```

The expected result is: Syntax error because the if block should have braces.
The actual result is: `true`

**Comment by mhagmajer** [comment]
Yes, the braces should be required at the parser level - `if (condition)` is an incomplete expression

**Comment by czerwinskilukasz1** [comment]
> Yes, the braces should be required at the parser level - `if (condition)` is an incomplete expression

The main thing is that `if (condition)` is a... valid **function** call - `if` is a resource (function) and it can be called with a parameter, same as `toString` can.
I added an extra check in parser for `if`, `for`, `while` and other similar resources.
