### ISSUE TITLE
at should throw if the key is missing

### ISSUE THREAD

**Issue by mhagmajer** [xFAANG/askql#404]
```
ask {
    const marta = { firstName: 'Marta' }
    marta:at('firstName3')
}
```
returns `null` (empty) but an error was expected (playground with AskVM v. 1.2.0)

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 what's your opinion about this?

**Comment by mhagmajer** [comment]
I'd really like not to have two empty values like in JavaScript

**Comment by czerwinskilukasz1** [comment]
I'm fine with throwing as soon as we have `hasKey`: https://github.com/xFAANG/askql/issues/400

**Comment by czerwinskilukasz1** [comment]
`hasKey` is implemented, this is unblocked now.

**Comment by mhagmajer** [comment]
Place to fix that in code: https://github.com/xFAANG/askql/blob/master/src/askvm/resources/core/at.ts

**Comment by dastin-sandura** [comment]
I have created a pull request with a unit test for this case. I will appreciate if someone could verify if the test is correct 😄 
Next, I will work on changing the implementation of at to work as expected by the test

**Comment by dastin-sandura** [comment]
My pull request is ready for review 😃
