### ISSUE TITLE
AskQL issue template

### ISSUE THREAD

**Issue by Tuhaj** [xFAANG/askql#407]
When creating a new issue it would be welcome to have prepared an issue template.
An issue template pops out when you click the button "New Issue"
Here is an example of such a template, I prepared already:
Your welcome with comments on what could be added or what could be removed 🤗

**Do you want to request a *feature* or report a *bug*? Please mark it with corresponding labels**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which version of AskQL, Node.js and Operating System are you using?**

**Comment by Tuhaj** [comment]
@mhagmajer @czerwinskilukasz1 any suggestions? Upvote please if you find it useful.

**Comment by czerwinskilukasz1** [comment]
@Tuhaj , these are great questions!

It seems to me we already have an issue for a feature request (https://github.com/xFAANG/askql/issues/128) and another one for a bug report (https://github.com/xFAANG/askql/issues/126).  Could you type your proposals there?
