### ISSUE TITLE
Implement `div` resource for integer division

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#412]
Similarly to `times` or `divideBy` resource we want to have `div` resource for integer division, whose result should be basically equal to Javascript's `Math.floor(y/x)`.

Dear new contributor,

If you have any questions on how to start, please write a comment with a tag: @czerwinskilukasz1 or @mhagmajer, or join our Discord Community and let us know there. We will be very happy to help you start! :)

Cheers,
Łukasz (@czerwinskilukasz1)
AskQL Core Developer

**Comment by anushaNemilidinne** [comment]
@czerwinskilukasz1  Hello ! I would like to contribute to this but this is my first time. Could you please help me in getting it started. Thanks!

**Comment by czerwinskilukasz1** [comment]
Hello @anushaNemilidinne ! Welcome to AskQL repository :)
Sure, I will help you in getting started. 

There is a module in the repository called AskVM. It has so called resources, which are like functions that you can call in programs written in AskScript language.
In this task we want to add `div` resource. You can `times` (src/askvm/resources/math/times.ts) and `divideBy` (src/askvm/resources/math/divideBy.ts) and write `div` in a similar manner. Sounds good? If you are unsure, let me know too!

**Comment by anushaNemilidinne** [comment]
Thanks @czerwinskilukasz1 for the information. I have never worked on AskScript language. But I will definitely try to get an overview of it and start working on the task. Is there any deadline for completing this ?

**Comment by czerwinskilukasz1** [comment]
> Thanks @czerwinskilukasz1 for the information. I have never worked on AskScript language. But I will definitely try to get an overview of it and start working on the task. Is there any deadline for completing this ?

@anushaNemilidinne , we devised AskScript to look similar to Javascript. 
A more or less up-to-date documentation is here: https://www.notion.so/AskScript-a-human-friendly-language-for-AskQL-7c5e382df87a4015b44985391861f6a2#a4fa16cb02c34572824e6b0c42a639eb
There might be some pieces out of date, so let me know if you find them. 

We also have AskScript Playground, where you can try it out: https://cli.askql.org/ 
Let me know if you have comments on the Playground too!

As for deadline, I think it's always good to set one to keep yourself motivated to make the contribution. Let's aim for submitting the first version of your change within 7 days.

**Comment by avats-dev** [comment]
Hey @anushaNemilidinne , are you still working on this?

**Comment by czerwinskilukasz1** [comment]
Hi @anushaNemilidinne, are you still there?  Let us know if you have more questions. It's good to ask :)

**Comment by anushaNemilidinne** [comment]
@czerwinskilukasz1 Sorry I could not respond to you in a while. I have not yet started working on this. I will start working on it today. Let me know if you have any concerns.

**Comment by czerwinskilukasz1** [comment]
@anushaNemilidinne , sounds good, thanks for letting me know. 
Please post any questions if you feel you are slowed down.
