### ISSUE TITLE
severity vulnerability in npm-watch

### ISSUE THREAD

**Issue by km4** [xFAANG/askql#435]
Hi, we need to think about `npm-watch` package. The package doesn't have any upgrade from the last 2 years.
@czerwinskilukasz1 you add this package but I don't see any usage. Maybe we can just remove from devDeps ?

![image](https://user-images.githubusercontent.com/1108808/89224523-e895b900-d5d8-11ea-8394-9e9fa9c5a7b9.png)

I can create PR for remove these packages. But maybe you need it for some reason :D

**Comment by czerwinskilukasz1** [comment]
@km4 , thanks for noticing. Go ahead and remove it.

**Comment by km4** [comment]
Fixed :)
![image](https://user-images.githubusercontent.com/1108808/89937395-55cacf00-dc15-11ea-8f75-879e9892004d.png)
