### ISSUE TITLE
Refactor let

### ISSUE THREAD

**Issue by YonatanKra** [xFAANG/askql#521]
Currently let holds the logic for `assign` and `const` which are different concerns.
Should write tests and implement `const` and `assign`.

**Comment by dastin-sandura** [comment]
Hey @YonatanKra can I take care of this issue? :)

**Comment by YonatanKra** [comment]
@dastin-sandura - the idea would be to split these into their own files.
Currently all of these logics are the same.

You can see it in this line:
`export { letRes as let, letRes as const, letRes as assign } from './let';`

Thing is, they are now quite different than each other. Enough to see the `if` statements inside the file like:
`if (code.name === 'assign') {`
`if (code.name === 'const') {`

So this task is a refactor task:

Split the `let` file into 3 files (const, assign, let) and extract a common module if needed.

They all should be covered with tests as well (preferably before the process begins). I've already added some tests in the `let.test.ts` file but since I "hopped in" just to add a feature, but note they are mixed (some test let, some test assign, some test const). They might not cover all of the use cases for the 3 resources.

**Comment by dastin-sandura** [comment]
Thank you! @YonatanKra 😄 this clears things up! I did not notice the ```export``` detail when I was analyzing the code so this explains a lot. I will submit changes today in the evening CET.
