### ISSUE TITLE
askql package - express middleware

### ISSUE THREAD

**Issue by mhagmajer** [xFAANG/askql#61]
Easy way to integrate AskQL with express

**Comment by YonatanKra** [comment]
@mhagmajer I can take this one.
I'm working on it this weekend.
My direction would be to create a middleware that does what the demoServer is doing "manually" - so ppl can just add a middleware, send a valid askql code, and it would just work.
I'll write the tests for this middleware by tomorrow night.
Once the tests are written, we can review the API. There are probably things I still don't understand/know regarding the askql syntax.

**Comment by mhagmajer** [comment]
Sounds good @YonatanKra! :)

**Comment by czerwinskilukasz1** [comment]
@YonatanKra, FWIW, in addition to the existing examples in master, I created a branch with a small server which accepts AskScript code and returns AskCode and the result (or an error): https://github.com/xFAANG/askql/blob/ask_server/src/demoAskServer.ts
