### ISSUE TITLE
:toString method returns a function when run in CLI

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#69]
When running `:toString` in CLI, when used in the last statement in `ask`, it returns a function.

![image](https://user-images.githubusercontent.com/12752520/83947797-907d4900-a819-11ea-99d8-9baa8ad82474.png)

Interesting enough, when running .ask file via `npm run ask`, it works correctly.

**Comment by mhagmajer** [comment]
Related to #46

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , #46 is fixed but `toString` behaves even worse - it throws an Uncaught Error: `Cannot call null`.

![image](https://user-images.githubusercontent.com/12752520/85745211-d127fe00-b705-11ea-8b11-1bed15dcabea.png)

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 this problem is only related to `toString`, probably due to name clash with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString, I checked that other resources like `lessThan` work correctly

**Comment by czerwinskilukasz1** [comment]
Indeed, `hasOwnProperty` results in the same error.

![image](https://user-images.githubusercontent.com/12752520/85788992-1f50f780-b72e-11ea-8dd8-d9ad94aa65ee.png)

I didn't know we allow accessing Javascript properties straight from AskVM.  Is it safe?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 we use object as the data structure for resources map. When you create an object in JavaScript using `{}` it derives all properties of `Object.prototype`. To avoid that you can use `Object.create(null)` but people really do as this is less convenient API

**Comment by czerwinskilukasz1** [comment]
Closing this one because #46 fixed the issue and opening a new one now:
https://github.com/xFAANG/askql/issues/228
