### ISSUE TITLE
Allow using double quotes for string literals

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#74]
Currently only single quotes are supported:
![image](https://user-images.githubusercontent.com/12752520/83952378-d695d500-a838-11ea-8690-67033855d389.png)

Using double quotes results in an error:

![image](https://user-images.githubusercontent.com/12752520/83952387-e57c8780-a838-11ea-8b72-0ba3ab409e9f.png)

**Comment by mhagmajer** [comment]
Can you please elaborate on the argument for adding another construction for string literals? Modern code formatting tools such as prettier change the code so that only one construct is used anyway.

**Comment by Tuhaj** [comment]
I like the idea of using single quotes only, as I understood this is a feature of the language, that takes the burden of making constant choices "single or double?". Single!

**Comment by czerwinskilukasz1** [comment]
OK, closing this one.
