### ISSUE TITLE
Run prettier automatically

### ISSUE THREAD

**Issue by Tuhaj** [xFAANG/askql#77]
<img width="607" alt="Screenshot 2020-06-07 at 15 57 12" src="https://user-images.githubusercontent.com/6118271/83970849-3db69680-a8d8-11ea-8190-c34d2fddb7d8.png">
Otherwise, GitHub will keep reminding us about this with this red flag.

**Comment by mhagmajer** [comment]
@YonatanKra feel free to use this issue to write down plans for prettier

**Comment by YonatanKra** [comment]
@mhagmajer 
I've added a PR for CI.
I'll add prettier to the CI file once we approve the CI flow.
After the change to this issue, the CI will look like this:
1. npm install
1. build ask prettier plugin
1. run prettier
1. run build:test
1. commit prettier changes (using `git-auto-commit-action`)
What do you think?
