### ISSUE TITLE
Running double and sometimes triple the amount of tests

### ISSUE THREAD

**Issue by YonatanKra** [xFAANG/askql#86]
![image](https://user-images.githubusercontent.com/6459899/84114500-2640f000-aa35-11ea-9f73-654e45739462.png)
In the above image, you can see a search for one file in the CI logs. 
It shows it runs both the `ts` test and the compiled `js` test.
It is also the same for other files.

**Comment by mhagmajer** [comment]
Right, seems like some of these we can ignore. Thanks for posting, @YonatanKra !
