### ISSUE TITLE
Only *.test.ts files use jasmine2 runner in Jest

### ISSUE THREAD

**Issue by YonatanKra** [xFAANG/askql#89]
When running tests I see a strange issue.
Here's my test:
```
it('should run a simple query', function () {
    expect(false).toEqual(true);
  });
```
But when I run the tests I get that everything is passing:
![image](https://user-images.githubusercontent.com/6459899/84133616-0b2fa980-aa50-11ea-81ab-5fd1e5eca0a7.png)
I thought it is my test but - I've added the same expect to an existing test `src/askjsx/__tests__/render.test.tsx`:
```
import * as askjsx from '..';
import { toAskCode } from '../../askcode';
askjsx;

test('jsx', () => {
  const sum = <call name="sum" args={[4, 5]} />;
  expect(false).toEqual(true);
  expect(sum).toStrictEqual(
    toAskCode({
      name: 'call',
      params: [toAskCode({ name: 'get', params: ['sum'] }), 4, 5],
    })
  );
});
```
And now all 3 changed suites pass:
![image](https://user-images.githubusercontent.com/6459899/84133769-3c0fde80-aa50-11ea-95a2-4290b16abf2a.png)

**Comment by mhagmajer** [comment]
This has to do with the following condition in our test runner:

```ts
  if (testPath.endsWith('.test.ts')) {
    /* ... */
    return jasmine2(/* ... */);
  }
  /* ... */
  await askRunner(/* ... */);
```  

https://github.com/xFAANG/askql/blob/aca6b3b923fae74ffa8039e5866b0ef364c2a85d/src/test.jest.testRunner.ts#L269

**Comment by mhagmajer** [comment]
After making changes to test suite files, please remember to do `npm run tsc` or test with `npm run tsc:test` so that Jest runs the new test runner
